# Test try-catch alone
set calc new Calculator

try
    calc.divide 10 0
catch error
    print "Caught error:" error